/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminsRouteImport } from './routes/_authed/admins'
import { Route as AuthedTeamsIndexRouteImport } from './routes/_authed/teams/index'
import { Route as AuthedMembersIndexRouteImport } from './routes/_authed/members/index'
import { Route as AuthedTeamsTeamIdRouteImport } from './routes/_authed/teams/$teamId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminsRoute = AuthedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamsIndexRoute = AuthedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersIndexRoute = AuthedMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamsTeamIdRoute = AuthedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthedAdminsRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRoute
  '/members/': typeof AuthedMembersIndexRoute
  '/teams/': typeof AuthedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admins': typeof AuthedAdminsRoute
  '/': typeof AuthedIndexRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRoute
  '/members': typeof AuthedMembersIndexRoute
  '/teams': typeof AuthedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admins': typeof AuthedAdminsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/teams/$teamId': typeof AuthedTeamsTeamIdRoute
  '/_authed/members/': typeof AuthedMembersIndexRoute
  '/_authed/teams/': typeof AuthedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/admins' | '/teams/$teamId' | '/members/' | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/admins' | '/' | '/teams/$teamId' | '/members' | '/teams'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admins'
    | '/_authed/'
    | '/_authed/teams/$teamId'
    | '/_authed/members/'
    | '/_authed/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admins': {
      id: '/_authed/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthedAdminsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/': {
      id: '/_authed/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthedTeamsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/': {
      id: '/_authed/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthedMembersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamId': {
      id: '/_authed/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthedTeamsTeamIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminsRoute: typeof AuthedAdminsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedTeamsTeamIdRoute: typeof AuthedTeamsTeamIdRoute
  AuthedMembersIndexRoute: typeof AuthedMembersIndexRoute
  AuthedTeamsIndexRoute: typeof AuthedTeamsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminsRoute: AuthedAdminsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedTeamsTeamIdRoute: AuthedTeamsTeamIdRoute,
  AuthedMembersIndexRoute: AuthedMembersIndexRoute,
  AuthedTeamsIndexRoute: AuthedTeamsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
